### ISSUE TITLE
Автопроброс реакции и создание очереди

### ISSUE THREAD

**Issue by NargGM** [nekonungstvo/KMChat#6]
La_Volpe_262 - Сегодня в 15:43
у меня есть ещё одна идея
смотри, у нас есть функция getLocalRecipients, которая находит всех игроков в радиусе R 
что если сделать команду /throwreac R для ГМов, которая берёт всех игроков в радиусе R и за каждого кидает реакцию?
будет полезно?
Narg - Сегодня в 15:45
Конечно
Не в 100% случаев
еще бы очередность создавало
Само
Ну ты понял
La_Volpe_262 - Сегодня в 15:45
можно сортировать сообщения (( Херсгоры кидает 4dF(====) от хорошо (реакция). Результат: хорошо )) по убыванию реакций
да
ну это легко уже
Narg - Сегодня в 16:23
Плюс фичреквест еще,  если будешь делать архитектуру заранее
Сделать чтобы при одинаковых значениях перебрасывалась реакция
Но при этом чтобы в итоговой очереди подсвечивалось другим цветом реакции тех, чья реакция была одинаковой до перебросов

**Comment by NargGM** [comment]
Narg - Сегодня в 17:49
@La_Volpe_262 я думаю может лучше сделать множество ников
Туда гм забрасывает участников
Руками (ну ники вбивает)
И за них кидается реакция
По рейнджу не очень

**Comment by ghost** [comment]
Сделано.
